#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --cpus-per-task=20
#SBATCH --exclusive
#SBATCH --time=24:00:00
#SBATCH --mem=180g
#SBATCH -J prop0

make clean
make
./scalar-1d

cd /gpfs/dpirvu/free_field_correlations

perl -i.bak -pe 's/[ \t]+//g' t512*fft_fields.dat

perl -i -pe 's/\)\(/)\t(/g' t512*fft_fields.dat

