#!/bin/bash
## Script for PI cluster symmetry:
#SBATCH --partition=defq
#SBATCH --cpus-per-task=20
#SBATCH --exclusive
#SBATCH --time=5:00:00
#SBATCH --mem=180g
#SBATCH -J jup

module load jupyter
module load python/3.7

jupyter nbconvert --execute PeakCorrelator.ipynb --ExecutePreprocessor.timeout=-1
